name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (Ubuntu)
      if: matrix.os == ubuntu-latest
      run: |
          sudo apt -q update
          sudo apt -q install --no-install-recommends libgtk-3-dev
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: latest
        cache: true
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@v3
      if: matrix.os == ubuntu-latest
      with:
        name: parenthesis-linux
        path: target/debug/parenthesis
      if: matrix.os == windows-latest
      with:
        name: parenthesis-windows
        path: target/debug/parenthesis.exe
