name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (Ubuntu)
      run: |
          sudo apt -q update
          sudo apt -q install --no-install-recommends libgtk-3-dev libvulkan-dev
    - name: Build
      run: cargo build --verbose
